### ISSUE TITLE
Implement CMake File/s (CMakeLists.txt)

### ISSUE THREAD

**Issue by ZachUCLamparyk** [EECE3093C/under-the-c-desktop#12]
Create CMakeLists.txt files as necessary so that all of our .cpp and .h files can be compiled down to a single executable with a "make" command

**Comment by natruffles** [comment]
Does our dev container currently have CMake installed? This is important because when the professor uses our dev container to run our app, he needs to be able to easily use CMake to compile all of our cpp files together.  If our dev container doesn't have CMake, would somebody be able to create an issue to add it? Thanks.

**Comment by ZachUCLamparyk** [comment]
Yes our dev container has both CMake and CMake Tools extensions installed.

**Comment by JSmith2023** [comment]
I have set up the cmake github action to test your file, if you push to main, this should test the file. If that helps reduce debug time. I can also add functionality for your own test branch if that would help.
