### ISSUE TITLE
Generate a JSON file based off of user menu inputs

### ISSUE THREAD

**Issue by ZachUCLamparyk** [EECE3093C/under-the-c-desktop#20]
1. Learn the JSON format
2. Learn how to use C++ library to generate JSON files with well-named key-value pairs
3. After user is finished inputting parameters in the menu, generate a JSON file and prompt the user to go into their filesystem and move the generated JSON file to the microcontroller program directory

This JSON file should have key-value pairs such as:
"zipCode": "45219",
etc...

**Comment by natruffles** [comment]
Hi Zach, I found [this C++ library](https://github.com/nlohmann/json) that can be used to easily read and write JSON files. This will probably be what you want to use to get all of your user inputs to write into a JSON file. Since I am already using the [Arduino-JSON library](https://github.com/arduino-libraries/Arduino_JSON) in the controller repo, I should easily be able to parse a JSON file that you output from your repo.
